Get http://localhost:3000/api/clientes

###
POST http://localhost:4000/api/clientes
Content-Type: application/json

{
    "nombre": "Salome",
    "correo": "salo@hotmail.com"
}

###

PUT http://localhost:3000/api/clientes/45

###

DELETE http://localhost:3000/api/clientes/45